### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by Aurorxa** [gclm/gitfox#14]
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.ejlchina.okhttps.HttpResult.getBody()" is null

![image](https://user-images.githubusercontent.com/25677587/221319839-d47db396-86c1-436b-aa15-b575e56ddae6.png)

**Comment by gclm** [comment]
![image](https://user-images.githubusercontent.com/27618687/228429852-1053c6f7-ea25-4517-8869-2a8951680d82.png)
你按照教程重置一下服务试试
