### ISSUE TITLE
不兼容Android Studio Hedgehog | 2023.1.1 Canary 4

### ISSUE THREAD

**Issue by junerver** [gclm/gitfox#16]
Not compatible with the version of your running IDE (Android Studio Hedgehog | 2023.1.1 Canary 4)
貌似是因为最新的AS使用的是JDK17的原因么，期待作者大大更新，已经离不开这个插件了

**Comment by gclm** [comment]
我用的就是jdk17啊。
![image](https://github.com/gclm/gitfox/assets/27618687/8c2eaaee-23de-4328-b3ce-d67f4a013863)

**Comment by gclm** [comment]
刚已经看了一下，建议你换成正式版本，目前Canary 版本推测可能出现sdk不支持的情况，目前最新的sdk版本就是我用的那个
![image](https://github.com/gclm/gitfox/assets/27618687/b02ba380-9293-4455-bfd1-b502341ac93e)
