### ISSUE TITLE
Long Description中文乱码

### ISSUE THREAD

**Issue by zlwlevi** [gclm/gitfox#18]
![image](https://github.com/gclm/gitfox/assets/90399609/5c28edf9-618d-4a1e-938d-b17a6be0198c)
上面的description正常，而下面的中文显示不了。
![image](https://github.com/gclm/gitfox/assets/90399609/70858917-9325-41bb-8c82-4de2788cb872)

使用的版本：
IDEA 2023.3.2
Win11 23h2
gitfox 1.0.2

**Comment by gclm** [comment]
我本地看能复现不

**Comment by gclm** [comment]
不好意思，我三台电脑都没复现。2台mac，一台windows11 都没复现。有点奇怪，请问你现在还正常吗？

**Comment by zlwlevi** [comment]
是的，我本地一直都是这样子乱码。

**Comment by zlwlevi** [comment]
请问这两个输入框的编码处理是不是不一样？

**Comment by gclm** [comment]
编码处理是一样的，所以有点莫名其妙，你什么时候有时间我远程看一下
![image](https://github.com/gclm/gitfox/assets/27618687/8d111f32-4492-461d-b4e5-9d22e4080d28)

**Comment by gclm** [comment]
所以我有点莫名奇妙

**Comment by zlwlevi** [comment]
现在有时间，可以远程debug下。

**Comment by gclm** [comment]
> 现在有时间，可以远程debug下。

我wx: gclmit
