### ISSUE TITLE
Gitfox的远程JSON数据报错

### ISSUE THREAD

**Issue by AprilViolet** [gclm/gitfox#9]
远程的JSON数据报错了

![image](https://user-images.githubusercontent.com/40155496/182638893-357cfefc-a49a-4c18-a3cd-c9e3fe61e911.png)

![image](https://user-images.githubusercontent.com/40155496/182639065-f5700cc9-373a-4630-b281-e8e66ed89340.png)

是否可以把这些JSON数据存储在本地，这样可以解决远程网络带来我问题

**Comment by gclm** [comment]
针对coding 无法访问的问题你点击这个就可以了。
<img width="906" alt="image" src="https://user-images.githubusercontent.com/27618687/182745789-2576a232-c3e8-4c07-af9c-c397567db4c9.png">

**Comment by gclm** [comment]
对于你提出的配置文件，与插件最初的意愿不太符合，
1.  因为插件最终的想法是用户可以根据自己公司的需求自定义提交规范，只要按照我定义的配置规范就行。然后提交配置，
2. 针对这个场景如何采用本地配置配置多设备同步是个问题
3. 按照现在的配置把你的自定义配置放到内网gitlab中，就可以把整个规范推广到全公司了。

**Comment by AprilViolet** [comment]
感谢。了解了，如果是这样场景，确实文件配置在远程是不错的选择。
